version: '2'

networks:
  app:
    driver: bridge
    name: app

services:
  q1:
    image: 'rabbitmq'
    hostname: q1
    ports:
      - 8081:5672
      - 15672:15672
    networks:
      - app
    volumes:
      - ./config:/config
    environment:
      - RABBITMQ_ERLANG_COOKIE=ABC
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq1.conf
      - RABBITMQ_ENABLED_PLUGINS_FILE=/config/plugins.conf
  q2:
    image: 'rabbitmq'
    hostname: q2
    ports:
      - 8082:5672
    networks:
      - app
    volumes:
      - ./config:/config
    environment:
      - RABBITMQ_ERLANG_COOKIE=ABC
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq2.conf
      - RABBITMQ_ENABLED_PLUGINS_FILE=/config/plugins.conf
  q3:
    image: 'rabbitmq'
    hostname: q3
    ports:
      - 8083:5672
    networks:
      - app
    volumes:
      - ./config:/config
    environment:
      - RABBITMQ_ERLANG_COOKIE=ABC
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq3.conf
      - RABBITMQ_ENABLED_PLUGINS_FILE=/config/plugins.conf
