source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'rabbitmq-consumer (iOS)' do
    platform :ios, '11.0'
    pod 'RMQClient', '~> 0.11.0'
end


target 'rabbitmq-consumer (macOS)' do
    platform :macos, '12.0'
    pod 'RMQClient', '~> 0.11.0'
end